Name: Github-testing-pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Job1:
    name: Testing-GithubActions
    runs-on: ubuntu-latest

    steps:
      

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

  Job2:
    needs: Job1
    name: Terraform Install
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"

  Job3:
    needs: Job2
    name: Terraform Commands
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"

      - name: Terraform
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
